---
- import_tasks: update-cache.yml

# https://community.kde.org/Guidelines_and_HOWTOs/Flatpak
- name: Add repo flatpak 4 Ubuntu
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_release != 'focal'
  become: yes
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present
    update_cache: yes
  tags:
    - linux
    - flatpak
    - ubuntu
    - deb
    - repo

- name: Install Debian only package
  when: 
    - ansible_distribution == 'Debian'
  become: yes
  apt:
    name:
      - gnome-software-plugin-flatpak
    state: present
    install_recommends: yes
  tags:
    - linux
    - flatpak
    - install
    - debian
    - deb

# https://flatpak.org/setup/CentOS/
- name: Install flatpak 4 CentOS\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
  vars:
    # https://stackoverflow.com/a/47091066/5430535
    # https://github.com/ansible/ansible/issues/32532#issuecomment-341641007
    ansible_python_interpreter: /usr/bin/python2.7
  become: yes
  yum:
    name:
      - flatpak
      - xdg-utils
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
    state: present
  tags:
    - linux
    - flatpak
    - install
    - rhel
    - centos
    - yum
    - rpm

- name: Install snapd 4 any Linux distros
  when:
    - ansible_system == 'Linux'
    - not (ansible_pkg_mgr == 'yum')
  become: yes
  package:
    name:
      - flatpak
      - xdg-utils
      - xdg-desktop-portal
    state: present
  tags:
    - linux
    - flatpak
    - install

# https://flatpak.org/setup/Ubuntu/
# https://flatpak.org/setup/Fedora/
- name: Add the flathub flatpak repository
  when: ansible_system == 'Linux'
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
  tags:
    - linux
    - flatpak
    - install
    - config
    - repo
